name: deckOfCards
description: deck of cards for StageXL
version: 1.0.0
homepage: https://txtsme.com
author: SpivEgin <spivegin@txtsme.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
  stage_colors:
    git: https://github.com/rafflenext/stage_colors.git

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
